<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Services\DialecticalOracleService;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Artisan;

class ProveUniversal10000 extends Command
{
    protected $signature = 'dialectic:prove-universal-10000';
    protected $description = 'Run the ultimate 10,000-axiom dialectical test against all 88 branches of human science.';
    protected $oracleService;

    public function __construct(DialecticalOracleService $oracleService)
    {
        parent::__construct();
        $this->oracleService = $oracleService;
    }

    public function handle()
    {
        $this->info('Reseeding the foundational logic database...');
        Artisan::call('db:seed', ['--class' => 'KnowledgeAxiomsSeeder']);
        $this->info('Database perfectly reseeded with foundational axioms.');

        $this->info('Starting the Universal Dialectical Test from total_science_test.json...');

        $outputFile = base_path('Dialectical_Book_of_Proofs.md');
        $jsonFile = base_path('scratch/total_science_test.json');
        
        if (!File::exists($jsonFile)) {
            $this->error("scratch/total_science_test.json not found!");
            return;
        }

        $questions = json_decode(File::get($jsonFile), true);

        $header = "# 📚 The Universal Dialectical Book of Proofs\n\n";
        $header .= "> **Autonomously generated by the Zmzir Dialectical Engine.**\n";
        $header .= "> *This document contains tests across all scientific branches dynamically pulled from the database.*\n\n";
        $header .= "---\n\n";
        File::put($outputFile, $header);

        $totalTested = 0;
        $resolvedCount = 0;
        $unknownCount = 0;

        foreach ($questions as $index => $q) {
            $totalTested++;
            $thesis = $q['query'];
            $this->line("   [{$totalTested}/" . count($questions) . "] Proving: {$thesis}");

            try {
                $proof = $this->oracleService->synthesizeProof($thesis);

                if ($proof === null) {
                    $status = 'Unknown';
                    $formattedEngineOutput = "**Engine Status: Unknown**\n\n[HALT] The Dialectical Engine could not synthesize a proof because it lacks the foundational knowledge axioms for this specific theorem, or it is chaotic. Deferring to Pancracy expert consensus.";
                    $unknownCount++;
                } else {
                    $status = 'synthesized_thesis';
                    $formattedEngineOutput = $proof;
                    $formattedEngineOutput .= "\n\n**Engine Status**: `{$status}`\n";
                    $resolvedCount++;
                }

            } catch (\Exception $e) {
                $formattedEngineOutput = "**Engine Error:** " . $e->getMessage();
                $status = 'error';
            }

            $consensusText = $q['trusted_consensus'] ?? $q['query'];

            $md = "### **Theorem {$totalTested}: {$q['title']}**\n\n";
            $md .= "---\n\n";
            $md .= "#### 🤖 Zmzir Dialectical Engine Output:\n\n";
            $md .= $formattedEngineOutput . "\n";
            $md .= "---\n\n";
            $md .= "#### 🌐 Trusted Scientific Website Consensus:\n";
            $md .= "*Source: Extracted Consensus*\n\n";
            $md .= "> **Consensus:** " . $consensusText . "\n\n";
            $md .= "<br><br>\n\n";

            File::append($outputFile, $md);
        }

        $this->info("Successfully generated {$totalTested} proofs. Wrote to Dialectical_Book_of_Proofs.md");
        $this->info("Resolved: {$resolvedCount}, Unknown (Halt): {$unknownCount}");
    }
}
