<?php

namespace App\Services\Dialectical;

/**
 * DYNAMIC SYNTAX GENERATOR — Dialectical Engine v3
 *
 * Renders academic-grade proof formatting:
 * - Truth tables (for logic)
 * - Algebraic step derivations (for math & science)
 * - Full proof assembly with phase headers
 *
 * All output is dynamic — no hardcoded proof content here.
 * Content is injected by the solvers from DB axiom fields.
 */
class DynamicSyntaxGenerator
{
    /**
     * Render a Markdown truth table with dynamic headers and rows.
     * Headers are passed from the solver (never hardcoded here).
     *
     * @param string[] $headers  Column names
     * @param array    $rows     Rows as indexed arrays (values in same order as headers)
     */
    public function renderTruthTable(array $headers, array $rows): string
    {
        // Header row
        $md  = '| ' . implode(' | ', array_map(fn($h) => "**{$h}**", $headers)) . " |\n";
        // Separator row — aligned
        $md .= '|' . implode('|', array_map(fn($h) => ':' . str_repeat('-', max(5, strlen($h))) . ':', $headers)) . "|\n";

        foreach ($rows as $row) {
            $cells = array_values((array)$row);
            $md .= '| ' . implode(' | ', $cells) . " |\n";
        }

        return $md . "\n";
    }

    /**
     * Render a formal step-by-step algebraic derivation.
     * Each step has: ['step' => '1', 'action' => 'label', 'expression' => 'math']
     * The 'expression' field is always generated by the solver from DB axioms or CAS.
     *
     * @param array $steps  Array of step arrays with 'step', 'action', 'expression' keys
     *                      (also supports legacy ['action', 'expression'] format)
     */
    public function renderAlgebraicSteps(array $steps): string
    {
        $out = "";
        foreach ($steps as $step) {
            if (isset($step['step'])) {
                $stepNum = str_pad("Step {$step['step']}:", 10);
                $actionName = $step['action'] ?? $step['label'] ?? 'Derivation Step';
                $action  = str_pad("[{$actionName}]", 36);
                $expr = $step['expression'] ?? $step['expr'] ?? '';
                $out .= "  {$stepNum} {$action}  {$expr}\n";
            } else {
                // Legacy format
                $actionName = $step['action'] ?? $step['label'] ?? null;
                if ($actionName) {
                    $out .= "  // " . $actionName . "\n";
                }
                $out .= "  " . ($step['expression'] ?? $step['expr'] ?? '') . "\n";
            }
        }
        $out .= "";
        return $out;
    }

    /**
     * Assemble the full three-phase proof block.
     * This is a structural wrapper — all text content must be passed in by solvers.
     *
     * @param string $title   Proof title (from domain['name'])
     * @param string $phase1  Phase 1 markdown content
     * @param string $phase2  Phase 2 markdown content
     * @param string $phase3  Phase 3 markdown content (null if halted)
     * @param string $icon    Branch icon from domain
     * @param string $axiomRef Academic reference from domain
     */
    public function assembleProof(
        string $phase1,
        string $phase2,
        string $phase3,
        string $title   = 'DIALECTICAL PROOF',
        string $icon    = '📜',
        string $axiomRef = ''
    ): string {
        $refNote = $axiomRef ? " `[{$axiomRef}]`" : '';
        return "### **{$icon} {$title}**{$refNote}\n\n"
             . "---\n\n"
             . "### 🔬 Phase 1 — Empirical Observation *(Trial & Error)*\n" . $phase1 . "\n\n"
             . "---\n\n"
             . "### 🧮 Phase 2 — Deductive Purification *(Logical / Algebraic Filtering)*\n" . $phase2 . "\n\n"
             . "---\n\n"
             . "### 🌍 Phase 3 — Inductive Synthesis *(Universal Scaling)*\n" . $phase3 . "\n";
    }

    /**
     * Render a set-theoretic Venn notation for categorical syllogisms.
     * Subject ⊆ Middle ⊆ Predicate chain.
     */
    public function renderCategoricalChain(array $terms): string
    {
        return implode(' ⊆ ', array_map(fn($t) => "`{$t}`", $terms));
    }

    /**
     * Render a formal propositional logic argument in natural notation.
     */
    public function renderArgument(string $major, string $minor, string $conclusion): string
    {
        $pad = max(strlen($major), strlen($minor), strlen($conclusion));
        return ""
             . "  Major Premise:  " . str_pad($major, $pad) . "\n"
             . "  Minor Premise:  " . str_pad($minor, $pad) . "\n"
             . "  " . str_repeat('─', $pad + 18) . "\n"
             . "  ∴ Conclusion:   " . $conclusion . "\n"
             . "\n";
    }
}
